Added github actions to perform code/flows analysis (#7)
* Added github actions to perform code/flows analysis

* Added logic to make validation/actual deployment

diff --git a/.github/actions/authorizeOrg/action.yml b/.github/actions/authorizeOrg/action.yml
--- a/.github/actions/authorizeOrg/action.yml
+++ b/.github/actions/authorizeOrg/action.yml
@@ -50,38 +50,32 @@ runs:
         TARGET_ORG_PASSWORD: ${{ inputs.targetOrgPassword }}
         TARGET_ORG_AUTH_URL: ${{ inputs.targetOrgAuthUrl }}
       run: |
-        # load functions to authorize SF environment in different ways
+        # Load functions to authorize SF environment
         source "${AUTH_UTILS_SCRIPT_PATH}"
 
-
-        # check if target org credentials are provided
+        # Identifying appropriate authorization function
         if [[ ${TARGET_ORG_USERNAME:+1} && "$TARGET_ORG_USERNAME" != "none" && \
               ${TARGET_ORG_PASSWORD:+1} && "$TARGET_ORG_PASSWORD" != "none" ]] ; then
 
           echo "⏳ Trying to authorize with provided target org username and password..."
 
-          authorizeWithCredentials \
+          authorize_with_credentials \
               "$TARGET_ORG_USERNAME" \
               "$TARGET_ORG_PASSWORD" \
               "TARGET_ORG_URL" \
               "$TARGET_ORG_ALIAS"
 
-        # check if target org authorization URL is provided
         elif [[ ${TARGET_ORG_AUTH_URL:+1} && "$TARGET_ORG_AUTH_URL" != "none" ]] ; then
-
           echo "⏳ Trying to authorize with provided target org authorization URL..."
 
-          authorizeWithAuthUrl \
+          authorize_with_auth_url \
               "$TARGET_ORG_AUTH_URL" \
               "$TARGET_ORG_ALIAS"
-
         else
-
-          echo "🚩 None of valid authorization params are provided. Authorization is not performed."
-
+          echo "❌ ERROR: None of valid authorization params are provided. Authorization is not performed."
+          exit 1
         fi
         
-
-        # set environment authorization details in outputs
+        # Set environment authorization details in outputs
         echo "targetOrgAlias=$TARGET_ORG_ALIAS" >> $GITHUB_OUTPUT
         echo "targetOrgUsername=$TARGET_ORG_USERNAME" >> $GITHUB_OUTPUT
